create table
  public.event (
    event_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    sup_id bigint not null,
    name text not null,
    total_spots integer not null default 0,
    min_age integer not null,
    activity_level integer not null default 0,
    location text not null,
    start_time timestamp with time zone not null,
    end_time timestamp with time zone not null,
    description text null,
    constraint event_pkey primary key (event_id),
    constraint event_event_id_key unique (event_id),
    constraint event_sup_id_fkey foreign key (sup_id) references supervisors (sup_id) ON DELETE CASCADE
  ) tablespace pg_default;

create table
public.organizations (
org_id bigint generated by default as identity,
created_at timestamp with time zone not null default now(),
name text not null,
city text not null,
verified boolean not null,
constraint organizations_pkey primary key (org_id),
constraint organizations_name_key unique (name),
constraint organizations_org_id_key unique (org_id)
) tablespace pg_default;

create table
  public.supervisor (
    sup_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    org_id bigint not null,
    sup_name text not null,
    email text not null,
    constraint supervisor_pkey primary key (sup_id),
    constraint supervisor_email_key unique (email),
    constraint supervisor_org_id_fkey foreign key (org_id) references organizations (org_id)
  ) tablespace pg_default;

create table
  public.volunteers (
    volunteer_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    city text not null,
    age integer not null,
    email text not null,
    constraint volunteers_pkey primary key (volunteer_id),
    constraint volunteers_email_key unique (email),
    constraint volunteers_volunteer_id_key unique (volunteer_id)
  ) tablespace pg_default;
create table
  public.volunteer_schedule (
    schedule_id bigint generated by default as identity,
    volunteer_id bigint not null,
    event_id bigint not null,
    constraint volunteer_schedule_pkey primary key (schedule_id),
    constraint volunteer_schedule_event_id_fkey foreign key (event_id) references event (event_id) on delete cascade,
    constraint volunteer_schedule_volunteer_id_fkey foreign key (volunteer_id) references volunteers (volunteer_id) on delete cascade
  ) tablespace pg_default;
